name: livecodes-preview

on: [pull_request]

jobs:
  build_and_prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: live-codes/preview-in-livecodes@v1
        with:
          install-command: "npm install"
          build-command: "npm run build"
          base-url: "https://{{LC::REF}}.preview-in-livecodes-demo.pages.dev"
